language: php

anguage: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  #- pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - phpcs --config-set default_standard PEAR
  - composer install

script:
  - phpcs --standard=build/travis-ci-phpcs.xml --extensions=php --ignore=vendor
  - phpunit --configuration tests/phpunit.xml