language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - phpcs --config-set default_standard PEAR
  - composer install

script:
  - phpcs --extensions=php --ignore=vendor
  - phpunit --configuration tests/phpunit.xml