language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - phpcs --config-set default_standard PEAR
  - composer install

script:
  - phpcs --standard=tests/phpcs.xml --extensions=php --ignore=config/,data/,public/,vendor/
  - phpunit --configuration tests/phpunit.xml