sudo: false

language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - composer install

script:
  - if [ $TRAVIS_PHP_VERSION != "hhvm" ]; then php vendor/bin/phpcs --config-set php_path php; fi
  - phpunit --configuration tests/phpunit.xml
  - php vendor/bin/phpcs  --standard=tests/phpcs.xml --standard=PEAR --report=summary -np

