<h1>Objetos</h1>
<div class="row">
    <div class="col-md-12 ">
        <div class="panel-body">
            <div class="row clearfix">
                <div class="col-sm-12">
                    <h3>Nuevo Objeto</h3>
                </div>                
                    <?php $form= $this->form; $form->prepare();?>
                    <?php echo $this->form()->openTag($form); ?>
                <div class="col-sm-1">
                    <div class="form-group">
                        <label >
                            <?php
                                $objetos_actividad_id = $form->get('objetos_actividad_id');
                                echo $objetos_actividad_id->getLabel();
                            ?>
                        </label>
                        <?php
                            echo $this->formInput($objetos_actividad_id);
                            echo $this->formElementErrors($objetos_actividad_id);
                        ?>
                    </div>
                </div>
                <div class="col-sm-1">
                    <div class="form-group">
                        <label >
                            <?php
                                $objetos_id = $form->get('objetos_id');
                                echo $objetos_id->getLabel();
                            ?>
                        </label>
                        <?php
                            echo $this->formInput($objetos_id);
                            echo $this->formElementErrors($objetos_id);
                        ?>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label >
                            <?php
                                $objetos_nombre = $form->get('objetos_nombre');
                                echo $objetos_nombre->getLabel();
                            ?>
                        </label>
                        <?php
                            echo $this->formInput($objetos_nombre);
                            echo $this->formElementErrors($objetos_nombre);
                        ?>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                            <label >
                                <?php
                                    $objetos_tipo = $form->get('objetos_tipo');
                                    echo $objetos_tipo->getLabel();
                                ?>
                            </label>
                            <?php
                                echo $this->formElement($objetos_tipo);
                                echo $this->formElementErrors($objetos_tipo);
                            ?>
                        </div>
                </div>
                <div class="col-sm-1">
                    <div class="form-group">
                        <label >
                            &nbsp;
                        </label>
                        <?php echo $this->formSubmit($form->get('guardar'));?>
                    </div>
                </div>
                
                <?php echo $this->form()->closeTag();  ?>
            </div> 
        </div> 
    </div> 
</div>

<h3>Listado de Objetos</h3>

<div class="row">
    <table class="table">
     <tr>
         <th>Actividad</th>
         <th>ID</th>
         <th>Nombre</th>
         <th>Tipo</th>
         <th>&nbsp;</th>
     </tr>
     <?php foreach ($this->objetos as $key => $objeto) : ?>
     <tr>
         <td><?php echo $this->escapeHtml($objeto->getObjetosActividadId());?></td>
         <td><?php echo $this->escapeHtml($objeto->getObjetosId());?></td>
         <td><?php echo $this->escapeHtml($objeto->getObjetosNombre());?></td>
         <td>
            <?php
                switch ($objeto->getObjetosTipo()) {                    
                    case 'T':
                        echo 'Transacción';
                        break;

                    case 'WP':
                        echo 'Web Panel';
                        break;

                    case 'PR':
                        echo 'Procedimiento';
                        break;

                    case 'ATR':
                        echo 'Atributo';
                        break;

                    case 'TBL':
                        echo 'Tabla';
                        break;
                    
                    default:
                        echo $objeto->getObjetosTipo();
                        break;
                }
            ?>
        </td>
         <td>
            <button type="button" class="btn btn-primary" onclick="window.location='<?php echo $this->basePath() ?>/application/objetos/editar/<?php echo $objeto->getObjetosId() ?>';event.stopPropagation();return false;"><i class="glyphicon glyphicon-edit"></i></button>
            <button type="button" class="btn btn-danger" onclick="window.location='<?php echo $this->basePath() ?>/application/objetos/eliminar/<?php echo $objeto->getObjetosId() ?>/<?php echo $this->actividad_id ?>';event.stopPropagation();return false;"><i class="glyphicon glyphicon-trash"></i></button>
            <button type="button" class="btn btn-success" onclick="window.location='<?php echo $this->basePath() ?>/application/objetos/etiquetas/<?php echo $objeto->getObjetosId() ?>';event.stopPropagation();return false;"><i class="glyphicon glyphicon-tags"></i></button>
         </td>
     </tr>
     <?php endforeach; ?>
    </table>
</div>