<?php if ($this->title){$this->headTitle()->append($this->title);} ?>
<h1><span class="zf-green"><?php echo $this->title;?></span></h1>
<br>
<table class="table table-hover demo-table-search" id="tablaObjetos">
    <thead>
        <tr>
            <th>ID</th>
            <th>Tipo</th>
            <th>Nombre</th>
            <th>Etiquetas</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->objetos as $key => $objeto) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($objeto->getObjetosId());?></td>
            <td>
                <?php if($objeto->getTipoObjetoIcono() != ""){?>
                <img width="16px" src="<?php echo $this->basePath('img/tipo_objeto/'.$this->escapeHtml($objeto->getTipoObjetoIcono())) ?>" alt="Zend Framework 2"/>
                <?php }?>
                <?php echo $this->escapeHtml($objeto->getTipoObjetoNombre());?>
            </td>                    
            <td><?php echo $this->escapeHtml($objeto->getObjetosNombre());?></td>
            <td> 
                <?php 
                    $etiquetas =  $this->RetornaEtiquetas($objeto->getObjetosId()); 
                ?>
                <?php foreach ($etiquetas as $keyy => $etiqueta) : ?>
                    <a href="<?php echo $this->basePath() ?>/application/etiquetas/objetos/<?php echo $etiqueta->getEtiquetasId() ?>" class=" btn-lg" >                       
                        <?php echo $etiqueta->getEtiquetasNombre();?>
                    </a>
                <?php endforeach; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>