<div class="jumbotron">
    <h2>
        <?php echo sprintf($this->translate('Bienvenido a %sReminder%s'), '<span class="zf-green">', '</span>') ?>
    </h2>
    <p>
        <?php echo sprintf($this->translate('%sReminder%s. Te ayuda a recordar lo objetos de GeneXus modificados durante la resolución de tus actividades. Esta aplicación está creada en PHP, MySQL sobre Zend Framework 2.'), '<a href="https://github.com/Escipion25/Reminder" target="_blank">', '</a>') ?>
    </p>    
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Actividades') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?php echo sprintf($this->translate('Gestionas tus actividades. Agrega los objetos que modificas, asçi los recordarás a la hora de hacer los pases.')) ?>
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="<?php echo $this->url('actividades', array('controller' => 'actividades', 'action' => 'index'))?>" >
                        <?php echo $this->translate('Gestionar') ?> &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Etiquetas') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?php echo sprintf($this->translate('Asocia objetos a una palabra clave o etiqueta para facilitar su búsqueda.')) ?>
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="<?php echo $this->url('etiquetas', array('controller' => 'etiquetas', 'action' => 'index'))?>" >
                        <?php echo $this->translate('Ver') ?> &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Colaborar') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <div class="col-md-8">
                    <?php echo sprintf($this->translate('Reminder es una aplicaión de código abierto, puedes colaborar haciendo fork al repositorio de %sGitHub%s.'), '<a href="https://github.com/Escipion25/Reminder" target="_blank">', '</a>') ?>
                    </div>
                    <a href="https://github.com/Escipion25/Reminder" target="_blank">
                        <img align="right" src="<?php echo $this->basePath('img/logo/original.png') ?>"  height="100" width="100">
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>
