<?php 
	if ($this->title){
		$this->headTitle()->append($this->title);
	}
?>

<h1>
	<span class="zf-green">
		<?php echo $this->translate($this->title);?>
	</span>
</h1>

<?php
	$form= $this->form;
	$form->prepare();
?>

<div class="row">
    <div class="col-md-6 ">        
        <div class="panel-body">
            <div class="row clearfix">
                <div class="col-sm-12">
					<?php echo $this->form()->openTag($form); ?>
						<div class="form-group">
					    	<label >
						    	<?php
						            $username = $form->get('username');
						            echo $username->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formInput($username);
						        echo $this->formElementErrors($username);
						    ?>
					  	</div>
					  	<div class="form-group">
					    	<label >
						    	<?php
						            $password = $form->get('password');
						            echo $password->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formInput($password);
						        echo $this->formElementErrors($password);
						    ?>
					  	</div>
					  	<div class="form-group">
					    	<label >
						    	<?php
						            $remember = $form->get('remember');
						            echo $remember->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formElement($remember);
						        echo $this->formElementErrors($remember);
						    ?>
					  	</div>
					  <?php echo $this->formElement($form->get('loginButton'));?>
					<?php echo $this->form()->closeTag();  ?>
				</div>
			</div>
		</div>		
	</div>
</div>