<?php if ($this->title){$this->headTitle()->append($this->title);} ?>
<h1>
    <span class="zf-green"><?php echo $this->title; ?></span>
</h1>
<?php
$form= $this->form;
$form->prepare();
?>
<div class="row">
		<div class="panel-body">
			<div class="row clearfix">
				<div class="col-sm-12">
				<?php echo $this->form()->openTag($form); ?>
				<div class="form-group">
					<label>
                        <?php
                            $actividades_fecha = $form->get('actividades_fecha');
                            echo $actividades_fecha->getLabel();
                        ?>
	                    </label>
	                    <?php
	                        echo $this->formInput($actividades_fecha);
	                        echo $this->formElementErrors($actividades_fecha);
	                    ?>
				</div>
				<div class="form-group">
                    <label>
                        <?php
                            $actividades_fecha_fin = $form->get('actividades_fecha_fin');
                            echo $actividades_fecha_fin->getLabel();
                        ?>
                    </label>
                    <?php
                        echo $this->formInput($actividades_fecha_fin);
                        echo $this->formElementErrors($actividades_fecha_fin);
                    ?>
                </div>

				<?php echo $this->form()->closeTag();  ?>
				</div>
			</div>
		</div>
	</div>



	 <button type="button" class="btn btn-info" onclick="window.location='<?php echo $this->basePath() ?>/application/actividades/bitacora2';event.stopPropagation();return false;"><i class="glyphicon glyphicon-list-alt"></i></button> 