<?php if ($this->title){$this->headTitle()->append($this->title);} ?>
<h1>
    <span class="zf-green"><?php echo $this->title; ?></span>
</h1>
<?php
 $form= $this->form;
$form->prepare();
?>
<div class="row">
    <div class="col-md-6 ">        
        <div class="panel-body">
            <div class="row clearfix">
                <div class="col-sm-12">
					<?php echo $this->form()->openTag($form); ?>
						<div class="form-group">
					    	<label >
						    	<?php
						            $actividades_id = $form->get('actividades_id');
						            echo $actividades_id->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formInput($actividades_id);
						        echo $this->formElementErrors($actividades_id);
						    ?>
					  	</div>
					  	<div class="form-group">
					    	<label >
						    	<?php
						            $actividades_nombre = $form->get('actividades_nombre');
						            echo $actividades_nombre->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formInput($actividades_nombre);
						        echo $this->formElementErrors($actividades_nombre);
						    ?>
					  	</div>
					  	<div class="form-group">
					    	<label >
						    	<?php
						            $actividades_responsable = $form->get('actividades_responsable');
						            echo $actividades_responsable->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formElement($actividades_responsable);
						        echo $this->formElementErrors($actividades_responsable);
						    ?>
					  	</div>
					  	<div class="form-group">
					    	<label >
						    	<?php
						            $actividades_reporta = $form->get('actividades_reporta');
						            echo $actividades_reporta->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formInput($actividades_reporta);
						        echo $this->formElementErrors($actividades_reporta);
						    ?>
					  	</div>
					  	<div class="form-group">
					    	<label >
						    	<?php
						            $actividades_area = $form->get('actividades_area');
						            echo $actividades_area->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formElement($actividades_area);
						        echo $this->formElementErrors($actividades_area);
						    ?>
					  	</div>
					  	<div class="form-group">
                            <label>
                                <?php
                                    $actividades_fecha = $form->get('actividades_fecha');
                                    echo $actividades_fecha->getLabel();
                                ?>
                            </label>
                            <?php
                                echo $this->formInput($actividades_fecha);
                                echo $this->formElementErrors($actividades_fecha);
                            ?>                            
                        </div>
                        <div class="form-group">
                            <label>
                                <?php
                                    $actividades_fecha_fin = $form->get('actividades_fecha_fin');
                                    echo $actividades_fecha_fin->getLabel();
                                ?>
                            </label>
                            <?php
                                echo $this->formInput($actividades_fecha_fin);
                                echo $this->formElementErrors($actividades_fecha_fin);
                            ?>                            
                        </div>
					  	<div class="form-group">
					    	<label >
						    	<?php
						            $actividades_estado = $form->get('actividades_estado');
						            echo $actividades_estado->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formElement($actividades_estado);
						        echo $this->formElementErrors($actividades_estado);
						    ?>
					  	</div>
					  
					  <?php echo $this->formElement($form->get('guardar'));?>
					<?php echo $this->form()->closeTag();  ?>
				</div>
			</div>
		</div>		
	</div>
</div>