<?php if ($this->title){$this->headTitle()->append($this->title);} ?>
<h1>
    <span class="zf-green"><?php echo $this->title; ?></span>
</h1>
<br>
<p>
    <a class="btn btn-primary" href="<?php echo $this->url('actividades', array('controller' => 'actividades', 'action'=>'crear2'));?>"><i class="glyphicon glyphicon-plus"></i> Nueva Actividad</a>
</p>
<br>
<table class="table table-hover demo-table-search" id="tablaActividades">
<thead>
    <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Fecha</th>
        <th>Estado</th>
        <th>&nbsp;</th>
    </tr>    
</thead>
<tbody>    
    <?php foreach ($this->actividades as $key => $actividad) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($actividad->getActividadesId());?></td>
        <td><?php echo $this->escapeHtml($actividad->getActividadesNombre());?></td>
        <td><?php echo $this->escapeHtml($actividad->getActividadesFecha());?></td>
        <td><?php if($actividad->getActividadesEstado() == "A"){echo"Activo";}else{echo"Finalizado";}?></td>
        <td>
            <button title="Listado de Objetos Asociados" type="button" class="btn btn-info" onclick="window.location='<?php echo $this->basePath() ?>/application/objetos/index/<?php echo $actividad->getActividadesId() ?>';event.stopPropagation();return false;"><i class="glyphicon glyphicon-list-alt"></i></button>
            <?php if($actividad->getActividadesEstado() == "F"):?>
                <button title="Activar" type="button" class="btn btn-success" onclick="window.location='<?php echo $this->basePath() ?>/application/actividades/activar/<?php echo $actividad->getActividadesId() ?>';event.stopPropagation();return false;"><i class="glyphicon glyphicon-ok"></i></button>
            <?php else:?>
                <button title="Finalizar" type="button" class="btn btn-warning" onclick="window.location='<?php echo $this->basePath() ?>/application/actividades/finalizardos/<?php echo $actividad->getActividadesId() ?>';event.stopPropagation();return false;"><i class="glyphicon glyphicon-remove"></i></button>        
            <?php endif?>
            <button title="Editar" type="button" class="btn btn-primary" onclick="window.location='<?php echo $this->basePath() ?>/application/actividades/editar2/<?php echo $actividad->getActividadesId() ?>';event.stopPropagation();return false;"><i class="glyphicon glyphicon-edit"></i></button>
            <button title="Eliminar" type="button" class="btn btn-danger" onclick="window.location='<?php echo $this->basePath() ?>/application/actividades/eliminar2/<?php echo $actividad->getActividadesId() ?>';event.stopPropagation();return false;"><i class="glyphicon glyphicon-trash"></i></button>
        </td>
    </tr>
    <?php endforeach; ?>
</tbody>
</table>