<?php echo $this->doctype(); ?>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <?php echo $this->headTitle()->prepend($this->translate('Reminder'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->appendStylesheet($this->basePath('/css/bootstrap.css'))
            ->appendStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css')
            ->appendStylesheet('https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css')
            ->appendStylesheet($this->basePath('css/dist/css/AdminLTE.min.css'))
            ->appendStylesheet($this->basePath('css/dist/css/skins/_all-skins.min.css'))
            ->appendStylesheet($this->basePath('css/plugins/iCheck/flat/blue.css'))
            ->appendStylesheet($this->basePath('css/plugins/morris/morris.css'))
            ->appendStylesheet($this->basePath('css/plugins/jvectormap/jquery-jvectormap-1.2.2.css'))
            ->appendStylesheet($this->basePath('css/plugins/datepicker/datepicker3.css'))
            ->appendStylesheet($this->basePath('css/plugins/daterangepicker/daterangepicker-bs3.css'))
            ->appendStylesheet($this->basePath('css/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'))
            // ->appendStylesheet($this->basePath('/css/bootstrap-theme.min.css'))
            // ->appendStylesheet($this->basePath('css/bootstrap/css/bootstrap.css'))
            // ->appendStylesheet($this->basePath('plugins/jquery-datatable/extensions/FixedColumns/css/dataTables.fixedColumns.min.css'))
            // ->appendStylesheet($this->basePath('plugins/jquery-datatable/media/css/jquery.dataTables.css'))
            // ->appendStylesheet($this->basePath('css/style.css'))

                     ;   ?>

        <!-- Scripts -->
        <?php echo $this->headScript()

            ->appendFile($this->basePath('js/jQuery-2.1.4.min.js'))
            ->appendFile('https://code.jquery.com/ui/1.11.4/jquery-ui.min.js')
            ->appendFile($this->basePath('css/bootstrap/js/bootstrap.min.js'))
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js')
            // ->appendFile($this->basePath('css/plugins/morris/morris.min.js'))
            ->appendFile($this->basePath('css/plugins/sparkline/jquery.sparkline.min.js'))
            ->appendFile($this->basePath('css/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'))
            ->appendFile($this->basePath('css/plugins/jvectormap/jquery-jvectormap-world-mill-en.js'))
            ->appendFile($this->basePath('css/plugins/knob/jquery.knob.js'))
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js')
            ->appendFile($this->basePath('css/plugins/daterangepicker/daterangepicker.js'))
            ->appendFile($this->basePath('css/plugins/datepicker/bootstrap-datepicker.js'))
            ->appendFile($this->basePath('css/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'))
            ->appendFile($this->basePath('css/plugins/slimScroll/jquery.slimscroll.min.js'))
            ->appendFile($this->basePath('css/plugins/fastclick/fastclick.min.js'))
            ->appendFile($this->basePath('css/dist/js/app.min.js'))
            // ->appendFile($this->basePath('css/dist/js/pages/dashboard.js'))
            ->appendFile($this->basePath('css/dist/js/widget.js'))
            ->appendFile($this->basePath('css/dist/js/demo.js'))
            ->appendFile($this->basePath('js/prueba.js'))
        ?>

  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

      
      <?php  echo $this->partial('layout/header'); ?>
      <?php  echo $this->partial('layout/sideBar'); ?>
     

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Dashboard
            <small>Control panel</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Small boxes (Stat box) -->
          <div class="container">
            <?php echo $this->content; ?>
            <hr>
            </div> <!-- /container -->
          <!-- Main row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 2.3.0
        </div>
        <p>&copy; 2005 - <?php echo date('Y') ?> by Cristhian García - Stalin Caiche. <?php echo $this->translate('All rights reserved.') ?></p>
      </footer>

      <!-- Control Sidebar -->
      <aside class="control-sidebar control-sidebar-dark">
        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
          <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
          <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <!-- Home tab content -->
          <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                    <p>Will be 23 on April 24th</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-user bg-yellow"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
                    <p>New phone +1(800)555-1234</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
                    <p>nora@example.com</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-file-code-o bg-green"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
                    <p>Execution time 5 seconds</p>
                  </div>
                </a>
              </li>
            </ul><!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Custom Template Design
                    <span class="label label-danger pull-right">70%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Update Resume
                    <span class="label label-success pull-right">95%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Laravel Integration
                    <span class="label label-warning pull-right">50%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Back End Framework
                    <span class="label label-primary pull-right">68%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                  </div>
                </a>
              </li>
            </ul><!-- /.control-sidebar-menu -->

          </div><!-- /.tab-pane -->
          <!-- Stats tab content -->
          <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->
          <!-- Settings tab content -->
          <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
              <h3 class="control-sidebar-heading">General Settings</h3>
              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Report panel usage
                  <input type="checkbox" class="pull-right" checked>
                </label>
                <p>
                  Some information about this general settings option
                </p>
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Allow mail redirect
                  <input type="checkbox" class="pull-right" checked>
                </label>
                <p>
                  Other sets of options are available
                </p>
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Expose author name in posts
                  <input type="checkbox" class="pull-right" checked>
                </label>
                <p>
                  Allow the user to show his name in blog posts
                </p>
              </div><!-- /.form-group -->

              <h3 class="control-sidebar-heading">Chat Settings</h3>

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Show me as online
                  <input type="checkbox" class="pull-right" checked>
                </label>
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Turn off notifications
                  <input type="checkbox" class="pull-right">
                </label>
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Delete chat history
                  <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                </label>
              </div><!-- /.form-group -->
            </form>
          </div><!-- /.tab-pane -->
        </div>
      </aside><!-- /.control-sidebar -->
      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>
    </div><!-- ./wrapper -->


  </body>
</html>

