<?php if ($this->title){$this->headTitle()->append($this->title);} ?>
<h1>
    <span class="zf-green"><?php echo $this->title; ?></span>
</h1>
<?php
 $form= $this->form;
$form->prepare();
?>
<div class="row">
    <div class="col-md-6 ">        
        <div class="panel-body">
            <div class="row clearfix">
                <div class="col-sm-12">
					<?php echo $this->form()->openTag($form); ?>
						<div class="form-group">
					    	<label >
						    	<?php
						            $usuarios_id = $form->get('usuarios_id');
						            echo $usuarios_id->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formInput($usuarios_id);
						        echo $this->formElementErrors($usuarios_id);
						    ?>
					  	</div>
					  	<div class="form-group">
					    	<label >
						    	<?php
						            $usuarios_username = $form->get('usuarios_username');
						            echo $usuarios_username->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formInput($usuarios_username);
						        echo $this->formElementErrors($usuarios_username);
						    ?>
					  	</div>
					  	<div class="form-group">
					    	<label >
						    	<?php
						            $usuarios_nombres = $form->get('usuarios_nombres');
						            echo $usuarios_nombres->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formInput($usuarios_nombres);
						        echo $this->formElementErrors($usuarios_nombres);
						    ?>
					  	</div>
					  	<div class="form-group">
					    	<label >
						    	<?php
						            $usuarios_estado = $form->get('usuarios_estado');
						            echo $usuarios_estado->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formElement($usuarios_estado);
						        echo $this->formElementErrors($usuarios_estado);
						    ?>
					  	</div>
					  
					  <?php echo $this->formElement($form->get('guardar'));?>
					<?php echo $this->form()->closeTag();  ?>
				</div>
			</div>
		</div>		
	</div>
</div>