<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Actividades') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?php echo $this->translate('Administra las Actividades registradas en la Aplicación') ?>
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="<?php echo $this->url('actividades', array('controller' => 'actividades', 'action' => 'listado'))?>" >
                        <?php echo $this->translate('Administrar') ?> &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Etiquetas') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?php echo $this->translate('Administra las Etiquetas registradas en la Aplicación') ?>
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="<?php echo $this->url('etiquetas', array('controller' => 'etiquetas', 'action' => 'listado'))?>" >
                        <?php echo $this->translate('Administrar') ?> &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Objetos') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?php echo $this->translate('Administra los Objetos registrados en la Aplicación') ?>
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="<?php echo $this->url('objetos', array('controller' => 'objetos', 'action' => 'listado'))?>" >
                        <?php echo $this->translate('Administrar') ?> &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Tipos de Objetos') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?php echo $this->translate('Administra los Tipos de Objetos disponibles en la Aplicación') ?>
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="<?php echo $this->url('tipoobjetos', array('controller' => 'tipoobjeto', 'action' => 'index'))?>" >
                        <?php echo $this->translate('Administrar') ?> &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Áreas') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?php echo $this->translate('Administra las Áreas disponibles en la Aplicación') ?>
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="<?php echo $this->url('areas', array('controller' => 'areas', 'action' => 'index'))?>" >
                        <?php echo $this->translate('Administrar') ?> &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Usuarios') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?php echo $this->translate('Administra los Usuarios de la Aplicación') ?>
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action' => 'index'))?>" >
                        <?php echo $this->translate('Administrar') ?> &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>
