<?php if ($this->title){$this->headTitle()->append($this->title);} ?>
<h1><span class="zf-green"><?php echo $this->escapeHtml($this->title); ?></span></h1>
<h3><span class="zf-green">Búsqueda</span></h3>
<div class="row">
    <div class="col-md-12 ">
        <div class="panel-body">
            <div class="row clearfix">                              
                <?php $formBusqueda = $this->formBusqueda; $form->prepare();?>
                <?php echo $this->form()->openTag($formBusqueda); ?>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label >
                                <?php
                                    $etiquetas_nombre = $formBusqueda->get('etiquetas_nombre');
                                    echo $etiquetas_nombre->getLabel();
                                ?>
                            </label>
                            <?php
                                echo $this->formInput($etiquetas_nombre);
                                echo $this->formElementErrors($etiquetas_nombre);
                            ?>
                        </div>
                    </div>
                    <div class="col-sm-1">
                        <div class="form-group">
                            <label >
                                &nbsp;
                            </label>
                            <?php echo $this->formElement($formBusqueda->get('guardar'));?>
                        </div>
                    </div>                
                <?php echo $this->form()->closeTag();  ?>
            </div> 
        </div> 
    </div> 
</div>
<h3><span class="zf-green">Listado de Objetos</span></h3>
<table class="table table-hover demo-table-search" id="tablaEtiquetas">
    <thead>
        <tr>
            <th>&nbsp;</th>
            <th>Objeto</th>            
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>            
    </thead>
    <tbody>
    <?php $form= $this->form; $form->prepare();?>
    <?php foreach ($this->objetos as $key => $objeto) : ?>
        <tr>
            <td>
                <?php if($objeto->getTipoObjetoIcono() != ""){?>
                <img width="16px" src="<?php echo $this->basePath('img/tipo_objeto/'.$this->escapeHtml($objeto->getTipoObjetoIcono())) ?>" alt="Zend Framework 2"/>
                <?php }?>
            </td>
            <td>
                <?php echo $this->escapeHtml($objeto->getObjetosNombre());?>
            </td>         
            <td>
                <?php echo $this->form()->openTag($form); ?>
                    <div class="col-md-6">
                        <?php
                            $objetos_id = $form->get('objetos_id');
                            $form->get('objetos_id')->setAttribute('value', $objeto->getObjetosId());
                            echo $this->formInput($objetos_id);
                            $etiquetas_nombre = $form->get('etiquetas_nombre');
                            echo $this->formInput($etiquetas_nombre);
                        ?>
                    </div>
                    <div class="col-md-1">
                        <?php echo $this->formElement($form->get('guardar'));?>
                    </div>
                <?php echo $this->form()->closeTag();  ?>
            </td>
            <td> 
                <?php 
                    $etiquetas =  $this->RetornaEtiquetas($objeto->getObjetosId()); 
                ?>
                <?php foreach ($etiquetas as $keyy => $etiqueta) : ?>
                    <a href="<?php echo $this->basePath() ?>/application/etiquetas/editar/<?php echo $etiqueta->getEtiquetasId() ?>" class=" btn-lg" >                       
                        <?php echo $etiqueta->getEtiquetasNombre();?>
                    </a>
                <?php endforeach; ?>
            </td>
        </tr>
     <?php endforeach; ?>            
    </tbody>
</table>