<?php if ($this->title){$this->headTitle()->append($this->title);} ?>
<h1><span class="zf-green"><?php echo $this->escapeHtml($this->title); ?></span></h1>
<br>
<h3>Etiqueta: <span class="zf-green"><?php echo $this->etiqueta->getEtiquetasNombre(); ?></span></h3>
<br>
<table class="table table-hover demo-table-search" id="tablaObjetos">
    <thead>
        <tr>
            <th>Actividad</th>
            <th>ID</th>
            <th>Nombre</th>
            <th>Tipo</th>
            <th>&nbsp;</th>
        </tr>            
    </thead>
    <tbody>
        <?php foreach ($this->objetos as $key => $objeto) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($objeto->getObjetosActividadId());?></td>
            <td><?php echo $this->escapeHtml($objeto->getObjetosId());?></td>
            <td><?php echo $this->escapeHtml($objeto->getObjetosNombre());?></td>
            <td>
                <?php if($objeto->getTipoObjetoIcono() != ""){?>
                <img width="16px" src="<?php echo $this->basePath('img/tipo_objeto/'.$this->escapeHtml($objeto->getTipoObjetoIcono())) ?>" alt="Zend Framework 2"/>
                <?php }?>
                <?php echo $this->escapeHtml($objeto->getTipoObjetoNombre());?>
            </td>
            <td>
                <button title="Editar Objeto" type="button" class="btn btn-primary" onclick="window.location='<?php echo $this->basePath() ?>/application/objetos/editar2/<?php echo $objeto->getObjetosId() ?>/<?php echo $this->etiqueta_id ?>';event.stopPropagation();return false;"><i class="glyphicon glyphicon-edit"></i></button>
                <button title="Eliminar Objeto" type="button" class="btn btn-danger" onclick="window.location='<?php echo $this->basePath() ?>/application/objetos/eliminar2/<?php echo $objeto->getObjetosId() ?>/<?php echo $this->etiqueta_id ?>';event.stopPropagation();return false;"><i class="glyphicon glyphicon-trash"></i></button>
            </td>
        </tr>
        <?php endforeach; ?>            
    </tbody>
</table>
