<?php if ($this->title){$this->headTitle()->append($this->title);} ?>
<h1><span class="zf-green"><?php echo $this->escapeHtml($this->title); ?></span></h1>
<?php
 $form= $this->form;
$form->prepare();
?>
<div class="row">
    <div class="col-md-6 ">        
        <div class="panel-body">
            <div class="row clearfix">
                <div class="col-sm-12">
					<?php echo $this->form()->openTag($form); ?>
						<?php 
							$objetos_id = $form->get('objetos_id');                            
                            echo $this->formInput($objetos_id);
						?>
						<div class="form-group">
					    	<label >
						    	<?php
						            $etiquetas_id = $form->get('etiquetas_id');
						            echo $etiquetas_id->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formInput($etiquetas_id);
						        echo $this->formElementErrors($etiquetas_id);
						    ?>
					  	</div>
					  	<div class="form-group">
					    	<label >
						    	<?php
						            $etiquetas_nombre = $form->get('etiquetas_nombre');
						            echo $etiquetas_nombre->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formInput($etiquetas_nombre);
						        echo $this->formElementErrors($etiquetas_nombre);
						    ?>
					  	</div>					  
					  <?php echo $this->formElement($form->get('guardar'));?>						
					<?php echo $this->form()->closeTag();  ?>
				</div>
			</div>
		</div>		
	</div>
</div>