<?php if ($this->title){$this->headTitle()->append($this->title);} ?>
<h1>
    <span class="zf-green"><?php echo $this->title; ?></span>
</h1>
<?php
 $form= $this->form;
$form->prepare();
?>
<div class="row">
    <div class="col-md-6 ">        
        <div class="panel-body">
            <div class="row clearfix">
                <div class="col-sm-12">
					<?php echo $this->form()->openTag($form); ?>
						<div class="form-group">
					    	<label >
						    	<?php
						            $tipo_objeto_id = $form->get('tipo_objeto_id');
						            echo $tipo_objeto_id->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formInput($tipo_objeto_id);
						        echo $this->formElementErrors($tipo_objeto_id);
						    ?>
					  	</div>
					  	<div class="form-group">
					    	<label >
						    	<?php
						            $tipo_objeto_nombre = $form->get('tipo_objeto_nombre');
						            echo $tipo_objeto_nombre->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formInput($tipo_objeto_nombre);
						        echo $this->formElementErrors($tipo_objeto_nombre);
						    ?>
					  	</div>
					  	<div class="form-group">
					    	<label >
						    	<?php
						            $tipo_objeto_icono = $form->get('tipo_objeto_icono');
						            echo $tipo_objeto_icono->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formInput($tipo_objeto_icono);
						        echo $this->formElementErrors($tipo_objeto_icono);
						    ?>
					  	</div>
					  	<div class="form-group">
					    	<label >
						    	<?php
						            $tipo_objeto_estado = $form->get('tipo_objeto_estado');
						            echo $tipo_objeto_estado->getLabel();
						        ?>
							</label>
						    <?php
						        echo $this->formElement($tipo_objeto_estado);
						        echo $this->formElementErrors($tipo_objeto_estado);
						    ?>
					  	</div>
					  
					  <?php echo $this->formElement($form->get('guardar'));?>
					<?php echo $this->form()->closeTag();  ?>
				</div>
			</div>
		</div>		
	</div>
</div>