<h1>Tipos de Objetos</h1>

<p>
    <a class="btn btn-success" href="<?php echo $this->url('tipoobjetos', array('controller' => 'tipoobjeto', 'action'=>'crear'));?>">Nuevo Tipo</a>
</p>

<table class="table">
 <tr>
    <th>ID</th>
    <th>Nombre</th>     
    <th>Estado</th>     
    <th>&nbsp;</th>
 </tr>
 <?php foreach ($this->tipos as $key => $tipo) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($tipo->getTipoObjetoId());?></td>
     <td><?php echo $this->escapeHtml($tipo->getTipoObjetoNombre());?></td>     
     <td><?php if($tipo->getTipoObjetoEstado() == "A"){echo"Activo";}else{echo"Inactivo";}?></td>
     <td>
        <button type="button" class="btn btn-primary" onclick="window.location='<?php echo $this->basePath() ?>/application/tipoobjeto/editar/<?php echo $tipo->getTipoObjetoId() ?>';event.stopPropagation();return false;"><i class="glyphicon glyphicon-edit"></i></button>
        <button type="button" class="btn btn-danger" onclick="window.location='<?php echo $this->basePath() ?>/application/tipoobjeto/eliminar/<?php echo $tipo->getTipoObjetoId() ?>';event.stopPropagation();return false;"><i class="glyphicon glyphicon-trash"></i></button>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>