<?php if ($this->title){$this->headTitle()->append($this->title);} ?>
<h1>
    <span class="zf-green"><?php echo $this->title; ?></span>
</h1>
<br>
<p>
    <a class="btn btn-primary" href="<?php echo $this->url('tipoobjetos', array('controller' => 'tipoobjeto', 'action'=>'crear'));?>"><i class="glyphicon glyphicon-plus"></i> Nuevo Tipo</a>
</p>
<br>
<table class="table table-hover demo-table-search" id="tablaTiposObjetos">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>     
            <th>Icono</th>     
            <th>Estado</th>     
            <th>&nbsp;</th>
        </tr>    
    </thead>
    <tbody>
        <?php foreach ($this->tipos as $key => $tipo) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($tipo->getTipoObjetoId());?></td>
            <td><?php echo $this->escapeHtml($tipo->getTipoObjetoNombre());?></td>     
            <td>
                <?php if($tipo->getTipoObjetoIcono() != ""){?>
                <img width="16px" src="<?php echo $this->basePath('img/tipo_objeto/'.$this->escapeHtml($tipo->getTipoObjetoIcono())) ?>" alt="Zend Framework 2"/>
                <?php }?>
                <?php echo $this->escapeHtml($tipo->getTipoObjetoIcono());?>
            </td>     
            <td><?php if($tipo->getTipoObjetoEstado() == "A"){echo"Activo";}else{echo"Inactivo";}?></td>
            <td>
                <button title="Editar Tipo de Objeto" type="button" class="btn btn-primary" onclick="window.location='<?php echo $this->basePath() ?>/application/tipoobjeto/editar/<?php echo $tipo->getTipoObjetoId() ?>';event.stopPropagation();return false;"><i class="glyphicon glyphicon-edit"></i></button>
                <button title="Eliminar Tipo de Objeto" type="button" class="btn btn-danger" onclick="window.location='<?php echo $this->basePath() ?>/application/tipoobjeto/eliminar/<?php echo $tipo->getTipoObjetoId() ?>';event.stopPropagation();return false;"><i class="glyphicon glyphicon-trash"></i></button>
            </td>
        </tr>
        <?php endforeach; ?>        
    </tbody>
</table>